---
title: Deliverable 4 - Video Pitch
author:
    - name: Christopher Torres, Kelechukwu Onyedeke, and Lindsey Marandina
      email: Torresc6@vcu.edu

---


[[Link to repository](https://github.com/cmsc-vcu/cmsc408-sp2025-del4-408-crew/tree/main)]

# Video pitch

This is 408 Crew's video pitch!

408 Crew consists of:

1. Christopher Torres
2. Kelechukwu Onyedeke
3. Lindsey Marandina

<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/1888231/sp/188823100/embedIframeJs/uiconf_id/28242251/partner_id/1888231?iframeembed=true&playerId=kaltura_player&entry_id=1_ls096t3m&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[hotspots.plugin]=1&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_q1mdh3mp" width="400" height="285" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="408 Crew Database Proposal"></iframe>


This video pitch proposal highlights 4 areas: its Problem Domain, the Need for the database, the Context, Scope, and Perspective of its application, and our team's motivation behind this choice. Each of these areas are explained in greater detail below.

## Problem Domain

A country club offers memberships to many different individuals who utilize the various different facilities and services offered. Club members pay monthly fees for their individual memberships and also may pay for other services and activities offered by the club. A database to manage the country club memberships would track various details of each member including names, contact information, membership status, membership type, payment history, attendance records, etc. The database would enable the club to maintain up to date and accurate member records from billing, activity tracking, and personal information reducing any errors.

## Need

The database is important to efficiently maintain the membership, as it safely stores member information (type of membership, membership payment history and billing, it helps keep track of events in which the country club has, and what member and type of membership access allows for attendance to the event  - Allows for personalized tracking of members preferred activities, easier to cater to them on an individual basis (Transaction is easier). Up to date contact information is also a big issue so storing the recent information of members is a problem that the database eliminates (doing so of course in a secure manner.)

## Context, Scope, Perspective

The DB is for Country Club Members and Country Club Owners. 

Country Club Members will receive additional expectations for their arrival and the duration of their stay due to these features. With isolated data used from purchase history while at the club for example, We will make it easier than ever before for more people to be treated with the expectation of their arrival. Such as the results of an increase in marketing for a simple item or rather the time and duration of their stay to even result in specific lightings and patterns for that viewer to create an anticipated ‘entrance’ over time.
For Country Club owners, Business owners can creatively use our tool to generate any data or statistics related to any Country club member. 

This data base also functions upon real time management and operations of the business. 
The database is for the management team of the Country club. A key feature of the database is for the coach in the domain of a sports team as the club manager has to provide access to the database to all country club employees and they can update, add, and delete things in and out of the database. 

Data retrieval is also given to specific department manager so they can easily access the information and relay it to their team.

I couldn't find any apps too similar to ours based upon a search with Chatgpt.



## Motivation

Our team selected this problem domain because it was designed around a useful scenario, our team members had former experience in the subject matter, and it could have real application due to its simplicity and usefulness. Operations derived from this database can be as complex as useful for any of the business’s needs with the data despite the initial appearance in the database design. By making the foundation of this data base revolving around a simple collection of data and the complex operations which can be creatively configured from that data. 
We chose this database due to KC proposing the idea. We can have a database that keeps track of members of a country club- we can account for their monthly club membership fee, times they attend the club a month etc.



# README




::: {style="background:lightgray; margin-left:20px; border-top: 3px solid black; border-bottom: 3px solid black; padding-left:20px; padding-right:20px"}
{{< include ../README.md >}}
:::




# Reflection

What did you like the most about this project?
: What I liked most about this project was that it creatively gave us experience with embedding videos from Zoom, and it reaffirmed many of the coding practices being taught such as getting in the habit of modifying the Readme. Designing our video pitch as a team was creative and fun, working through challenges and design flaws. Further exploring final designs in upcoming assignments is going to be exciting.

How are you finding Harmonize to host/facilitate discussions?  Is it helpful?
: Great! I actually really like Harmonize! It's fluid, factual, and an easy way to communicate! I wish there was a way for posts or comments to be more presentable instead of me having to click on each post to see its contents or subject matter especially. However, I can't name a better platform I have used. Harmonize really does a great job at being informative and clear cut.

How would you improve Harmonize so that it works better for discussions?
: If I could literally redesign the platform, I would suggest changing the presentation of posts as I wrote above. I would simply pull quotes from each and share those in a way users can click the intriguing ones and read or respond from those posts. This fixes the major issue of not even being able to tell the subject matter of a classmate's post without actually clicking on it! That makes functionally zero sense! Besides that, and a slight redesign in U.I., Harmonize is a pretty great platform.