---
title: Implementation - Deliverable 7
---

A country club offers memberships to many different individuals who utilize the various different facilities and services offered. Club members pay monthly fees for their individual memberships and also may pay for other services and activities offered by the club. A database to manage the country club memberships would track various details of each member including names, contact information, membership status, membership type, payment history, attendance records, etc. The database would enable the club to maintain up to date and accurate member records from billing, activity tracking, and personal information reducing any errors.

* [[Link to repository](https://github.com/cmsc-vcu/cmsc408-sp2025-semproj-408-crew)]
* [[Direct link to video pitch](https://github.com/cmsc-vcu/cmsc408-sp2025-semproj-408-crew)]
* [[Direct link to design video](https://github.com/cmsc-vcu/cmsc408-sp2025-semproj-408-crew)]
* [[Direct link to implementation video](https://github.com/cmsc-vcu/cmsc408-sp2025-semproj-408-crew)]

# Design video

 video presentation  summarize your implemention, how it went, how you design might have
needed to be modified during implementation, and your reflections on the overall process. 

<iframe id="kaltura_player" src=" LINK GOES HERE
" width="400" height="285" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="408 Crew Database Proposal"></iframe>
DEMONSTRATE your working implementation.

docker cp Data/members.csv mysql-container:/var/lib/mysql-files/
docker cp Data/events.csv mysql-container:/var/lib/mysql-files/
docker cp Data/payments.csv mysql-container:/var/lib/mysql-files/
docker cp Data/worker.csv mysql-container:/var/lib/mysql-files/
docker cp Data/attends.csv mysql-container:/var/lib/mysql-files/
docker cp Data/organizes.csv mysql-container:/var/lib/mysql-files/
docker cp Data/membership_type.csv mysql-container:/var/lib/mysql-files/
# Web interface design

Your report should explain how you implemented the web interface.  What tools did you use?  Why?

# Screenshots

For each of the major screens in your program, provide an image and an explanation of what the screen does or how it supports the user interface.

# Reports

Your web site should contain a Reports page with 20 queries selectable from a menu.  Each report should run.

# Future considerations

What needs to be done next to take your project to the next level? If you had more time, what would you do next?

# Reflections on the overall project

How did the project go? Did you achieve what you originally intended to build? If not, what kept you from achieving it?

Your report should touch on all the elements discussed in the project description.  You
can certainly refer to sections of previous reports.

This document should be STAND-ALONE. That is, you shouldn't need to refer to other documents
to get your points across.

See: <https://virginiacommonwealth.instructure.com/courses/113813/assignments/1075774>


# Reflection

How was your overall experience with this semester-long project?
: My overall experience was a positive one!

How did the homeworks and discussions prepare you (or not) for successful completion of this project?
: They helped me incredibly! I won't say the discussions were to influential, but I enjoyed completing them. The homeworks were definitely the most helpful in terms of staying on track and understanding the content.

What advice would you give to students working on this project in the future?
: I would give advice to keep up with the homework and start thinking about the project early, and preferably while you are completing the homeworks, as that will enable you to actually understand where each step comes into play.


# README

::: {style="background:lightgray; margin-left:20px; border-top: 3px solid black; border-bottom: 3px solid black; padding-left:20px; padding-right:20px"}
{{< include ../README.md >}}
:::


