# Kubernetes skeleton: deployment, service, optional HPA
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-ml-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e2e-ml
  template:
    metadata:
      labels:
        app: e2e-ml
    spec:
      containers:
      - name: e2e-ml
        image: YOUR_REGISTRY/e2e-ml-pipeline:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MODEL_URI
          value: "models:/YourModelName/Production"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: e2e-ml-service
spec:
  selector:
    app: e2e-ml
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: e2e-ml-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: e2e-ml-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60